# Generated by Django 3.2.8 on 2022-05-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='sqlite3.db',
        ),
    ]
