# Generated by Django 3.2.8 on 2022-01-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
    ]
