# Generated by Django 3.2.8 on 2022-01-25 12:09

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='id_nummber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(14)], verbose_name='id_nummber'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_nummber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(11)], verbose_name='phone_nummber'),
        ),
    ]
